In [1]:
# Theoretical Questions:

In [ ]:
# # 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis.
# # How does it enhance Python's capabilities for numerical operations?

# # Ans(1)

# # Purpose of NumPy:

# # Efficient Data Handling: NumPy provides an efficient way to store and manipulate large datasets using ndarrays (N-dimensional arrays).

# # Mathematical Operations: It offers a wide range of mathematical functions for operations on arrays and matrices.

# # Foundation for Other Libraries: Many data science libraries like Pandas, SciPy, and scikit-learn are built on top of NumPy.

# # Interfacing with C/C++ and Fortran: NumPy allows integration with code written in these languages for enhanced performance.

# # Advantages of NumPy:

# # Performance: NumPy arrays are more efficient than Python lists, especially for large datasets.

# # Convenience: It provides concise syntax for array operations, making code more readable and easier to write.

# # Vectorization: Operations are applied element-wise without explicit loops, improving performance.

# # Broadcasting: This feature allows operations on arrays of different shapes, simplifying many tasks.

# # Comprehensive Functions: NumPy includes a wide array of functions for mathematical, logical, and statistical operations.

# # Integration: Proficiency in NumPy facilitates learning and using other data science tools like Pandas and Matplotlib.

# # Community Support: It has a large community and extensive documentation for help and resources.

# # Enhancing Python’s Numerical Capabilities:

# # Efficient Data Structures: NumPy's ndarrays are faster and more memory-efficient than Python lists.

# # Mathematical Functions: It provides optimized functions for various mathematical operations.

# # Memory Management: NumPy arrays use less memory compared to equivalent Python lists.

# # Low-Level Integration: It allows the use of high-performance libraries and custom functions written in C/C++ and Fortran.

# # Array Broadcasting: Simplifies code by allowing operations on arrays of different shapes without complex loops.


# NumPy enhances Python's capabilities for numerical operations in several key ways:

# Efficient Data Structures
# ndarray: NumPy introduces ndarray (N-dimensional array), a powerful data structure optimized for numerical calculations. These arrays are more efficient in terms of memory usage and performance compared to Python lists, especially for large datasets.

# Performance Optimization
# Speed: NumPy arrays are implemented in C, allowing for faster computation. Operations on NumPy arrays are significantly faster than operations on Python lists due to the optimized C code running behind the scenes.
# Vectorization: NumPy supports vectorized operations, which means operations can be applied element-wise to entire arrays without the need for explicit loops. This not only speeds up the computation but also makes the code more readable and concise.

# Broad Functionality
# Mathematical Functions: NumPy provides a comprehensive set of mathematical functions, including linear algebra, random number generation, Fourier transforms, and more. These functions are highly optimized for performance.
# Broadcasting: Broadcasting allows NumPy to perform operations on arrays of different shapes and sizes. This feature simplifies many mathematical operations and reduces the need for complex, multi-dimensional loops.

# Memory Efficiency
# Contiguous Memory Layout: NumPy arrays are stored in contiguous blocks of memory, which improves cache efficiency and speeds up access times. This memory layout is more efficient compared to the scattered memory layout of Python lists.
# Homogeneous Data: NumPy arrays are homogeneous, meaning all elements in the array are of the same data type. This allows for more efficient storage and computation.

# Integration with Low-Level Languages
# C/C++ and Fortran Integration: NumPy can seamlessly interface with code written in C, C++, and Fortran. This allows developers to leverage high-performance libraries and custom functions, enhancing the computational capabilities of Python.

# Simplified Code
# Concise Syntax: NumPy provides a clear and concise syntax for numerical operations, making the code easier to write and understand. This simplification is particularly useful for scientific computing and data analysis, where complex operations are common.

# Ecosystem Support
# Foundation for Other Libraries: NumPy serves as the foundation for many other scientific and data analysis libraries in Python, such as SciPy, Pandas, and scikit-learn. Proficiency in NumPy ensures smoother learning and usage of these related tools.


In [3]:
# # 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one
# # over the other?

# # Ans(2)

# np.mean()
# Purpose: Calculates the arithmetic mean (simple average) of array elements.
# Syntax: np.mean(array, axis=None)
# Example:
#
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
mean = np.mean(arr)  # Result: 3.0

# np.average()
# Purpose: Calculates the weighted average of array elements.
# Syntax: np.average(array, axis=None, weights=None)
# Example:

import numpy as np
arr = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 1, 1, 1, 2])
weighted_avg = np.average(arr, weights=weights)  

# Weights:
# np.mean(): Does not use weights.
# np.average(): Can use weights to compute the average.

# Use Case:
# Use np.mean() for a simple average.
# Use np.average() when you need a weighted average.

# When to Use
# np.mean(): When you want the basic average without any weights.
# np.average(): When you need to consider the relative importance of elements using weights.


In [3]:
# 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 
# 1D and 2D arrays. 

# Ans(3)
# Reversing a NumPy array along different axes can be done using slicing and specialized NumPy 
# functions. Here’s how you can reverse arrays along different axes with examples for 1D and 2D arrays:

# Reversing a 1D Array
# Method: Slicing

# To reverse a 1D array, you can use slicing with a step of -1.
# Ex:- 

import numpy as np

arr_1d = np.array([1,2,3,4,5])
arr_1d[::-1]

# Reversing a 2D Array
# Method 1: Reversing Along the First Axis (Rows)

# To reverse a 2D array along the first axis (rows), you can use slicing with a step of -1 on
# the first axis.

arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d[::-1]



array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [4]:
# 4. How can you determine the data type of elements in a NumPy array? Discuss the importance of 
# data types in memory management and performance.

# Ans(4) To determine the data type of elements in a NumPy array, you can use the dtype attribute
# of the array. Here’s how you can do it:

import numpy as np 

arr = np.array([1,2,3,4])
print(arr.dtype)

# Data types in NumPy play a crucial role in memory management and performance optimization.
# Here’s a detailed discussion:

# Memory Management: Efficient data types save memory, crucial for large datasets.

# Performance: Smaller, appropriate data types can lead to faster computations and 
# better utilization of NumPy optimizations.

int64


In [ ]:
# 5. Define ndarrays in NumPy and explain their key features. How do they differ from standard 
# Python lists?

# Ans(5) ndarray stands for "N-dimensional array" and is the core data structure in NumPy.
# It is a powerful array object that provides fast and efficient operations on large datasets.

# Key Features of ndarrays:-

# Homogeneous Data Type:
# All elements in an ndarray have the same data type, ensuring efficient storage and computation.

# Multidimensional:
# ndarray can have any number of dimensions (axes), from 1D (like a list) to 
# multi-dimensional (2D, 3D, etc.).

# Fast and Memory Efficient:
# Operations on ndarrays are optimized and can be performed very quickly.
# Memory usage is more efficient compared to Python lists, especially for large datasets.

# Broadcasting:
# Allows operations on arrays of different shapes, aligning them as needed.

# Advanced Functions and Methods:
# NumPy provides numerous built-in functions for mathematical operations, statistics,
# linear algebra, and more.

# Differences Between ndarrays and Python Lists

# Data Type:
# ndarrays: Homogeneous, all elements have the same data type.
# Lists: Heterogeneous, can contain elements of different data types.

# Performance:
# ndarrays: Faster for numerical operations due to optimized C implementations.
# Lists: Slower for numerical operations because they are more general-purpose and flexible.

# Memory Usage:
# ndarrays: More memory-efficient due to fixed data types and contiguous memory allocation.
# Lists: Less memory-efficient due to the flexibility of storing different data types
# and non-contiguous memory allocation.

# Functionality:
# ndarrays: Supports broadcasting, vectorized operations, and many mathematical functions.
# Lists: Do not support broadcasting or vectorized operations. Mathematical operations must be done
# element-wise using loops or comprehensions.

# Slicing and Indexing:
# ndarrays: Advanced slicing and indexing capabilities, including multidimensional slicing.
# Lists: Basic slicing and indexing capabilities, less powerful for multidimensional data.

In [ ]:
# # 6.Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

# # Ans(6) 

# Memory Efficiency: NumPy arrays use contiguous memory blocks and homogeneous data types,
# leading to lower memory overhead compared to Python lists.

# Computational Efficiency: Vectorized operations and broadcasting in NumPy eliminate the need
# for explicit loops and improve performance.

# Rich Functionality: NumPy's built-in functions and methods are optimized for performance and
# can handle large datasets efficiently.

# Parallelism and Multithreading: NumPy leverages optimized libraries and parallel execution 
# to perform computations faster.


In [10]:
# 7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
# output.

# Ans(7)

# The vstack() and hstack() functions in NumPy are used to stack arrays vertically and horizontally, respectively. Here’s a detailed comparison and examples demonstrating their usage and output:

# vstack()
# Description: Stacks arrays in sequence vertically (row-wise).
# Use Case: Used when you want to combine arrays along the vertical axis (adding rows).
# Ex:-

import numpy as np

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

result = np.vstack((a, b))
print(result)


# hstack()
# Description: Stacks arrays in sequence horizontally (column-wise).
# Use Case: Used when you want to combine arrays along the horizontal axis (adding columns).
# Ex:-

import numpy as np

a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,0])

result = np.hstack((a, b))
print(result)


[[1 2 3 4 5]
 [5 6 7 8 9]]
[1 2 3 4 5 6 7 8 9 0]


In [16]:
# # # 8.Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
# # # array dimensions.

# # # Ans(8)

# # The fliplr() and flipud() methods in NumPy are used to flip arrays along different axes.
# Here’s a detailed explanation of their differences and their effects on arrays of various dimensions:

# # fliplr()
# # Description: Flips an array left to right (horizontally) along the second axis (axis=1).
# # Use Case: Used when you want to reverse the order of columns in a 2D array or higher-dimensional
# arrays where the second axis is considered.
# Ex:-

import numpy as np 
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

result = np.fliplr(arr)
result



# flipud()
# Description: Flips an array up to down (vertically) along the first axis (axis=0).
# Use Case: Used when you want to reverse the order of rows in a 2D array or higher-dimensional
# arrays where the first axis is considered.
# Ex-

import numpy as np 

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

result = np.flipud(arr)
result

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [23]:
# 9.Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?
# Ans(9)

# The array_split() method in NumPy is used to split an array into multiple sub-arrays.
# It is a versatile function that can handle both equal and unequal splits.
# Here's a detailed discussion on its functionality and how it handles uneven splits:

# Basic Usage
# The array_split() function allows you to specify the number of splits or the indices at
# which to split the array. It returns a list of sub-arrays.

# Syntax:
    # numpy.array_split(array, indices_or_sections, axis=0)
    
# array: The input array to be split.
# indices_or_sections: If an integer, it represents the number of equal or unequal sub-arrays to split into. If a list of indices, it represents the points at which the array is split.
# axis: The axis along which to split the array. Default is 0.


# Handling Uneven Splits
# When the number of splits does not divide the array evenly, array_split() handles the remainder
# by distributing it among the sub-arrays. The function tries to make the sub-arrays as equal as 
# possible.

# Ex-

import numpy as np

arr = np.array([1,2,3,4,5,6,7])

result = np.array_split(arr,6)
for i in result:
    print(i)

[1 2]
[3]
[4]
[5]
[6]
[7]


In [ ]:
#  10.Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute
#  to efficient array operations?

#  Vectorization

#  Concept:
#  Vectorization in NumPy refers to the process of performing operations on entire arrays without the need for explicit loops.
# It leverages underlying optimizations in NumPy's implementation (often in C) to execute operations efficiently.

#  Benefits:
#  Speed: Vectorized operations are much faster than equivalent operations implemented with Python loops.
# Code Simplicity: Eliminates the need for explicit loops, making the code more concise and easier to read.
#  Efficiency: Operations are performed at a lower level in optimized machine code, which is more efficient than high-level Python loops.

#  Broadcasting

#  Concept:
#  Broadcasting in NumPy allows operations on arrays of different shapes, by automatically expanding the smaller array to match the shape of the larger array.
#  It follows specific rules to align the shapes and apply the operations.

#  Rules:
# # If the arrays differ in their number of dimensions, the shape of the smaller array is padded with ones on its left side.
# # If the shape of the arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
# # If any dimension sizes are mismatched and neither is equal to 1, broadcasting will not be possible.

# # Benefits:
# # Flexibility: Allows operations between arrays of different shapes, saving the need to create explicitly matched shapes.
# # Memory Efficiency: Avoids creating large intermediate arrays, working instead with the existing array's data in an efficient manner.

# Contributions to Efficient Array Operations

# Performance Improvement:
# Both vectorization and broadcasting leverage NumPy’s underlying C-based implementation, which is optimized for performance.
# This results in significant speedups for array operations compared to native Python loops.

# Memory Efficiency:
# Broadcasting avoids the need for explicitly expanding smaller arrays to match larger arrays, which conserves memory.
# Vectorized operations work on the entire array directly, avoiding the overhead of iterating through individual elements.

# Code Simplicity:
# Eliminates the need for explicit loops and intermediate data structures, resulting in cleaner and more maintainable code.
# Easier to read and understand, particularly for complex mathematical and array operations.

# Parallelism:
# Under the hood, NumPy operations can leverage parallel processing capabilities of modern CPUs, further enhancing performance.

In [1]:
# Practical Questions

In [10]:
# 1. Create a 3x3 NumPy array with random integers between 1 and 100.
# Then, interchange its rows and columns.

# Ans(1)
import numpy as np

array = np.random.randint(1,101, size = (3,3))

array.T

array([[43, 72, 76],
       [26, 91, 92],
       [89, 16, 68]])

In [13]:
# 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array?

# Ans(2)
import numpy as np 

array_1d = np.arange(10)
array_1d

reshape_2x5 = array_1d.reshape((2,5))
reshape_2x5

reshape_5x2 = reshape_2x5.reshape((5,2))
reshape_5x2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [19]:
# 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it,
# resulting in a 6x6 array.

# Ans(3)
import numpy as np 

array_4x4 = np.random.rand(4,4)
array

array_6x6 = np.pad(array_4x4, pad_width = 1, mode = 'constant', constant_values = 0)
print(array_6x6)

[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.5085248  0.33496898 0.62154618 0.36542832 0.        ]
 [0.         0.40108244 0.71647438 0.76891122 0.55695911 0.        ]
 [0.         0.66261396 0.29824221 0.58732978 0.59067655 0.        ]
 [0.         0.93030759 0.2329902  0.93281518 0.19107301 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [25]:
# 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

# Ans(4)
import numpy as np

array = np.arange(10,61,5)
print(array)

[10 15 20 25 30 35 40 45 50 55 60]


In [31]:
# 5.Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
# (uppercase, lowercase, title case, etc.) to each element.

# Ans(5)
import numpy as np 

array = np.array(['python','numpy','pandas'])
print(array)

upper_array = np.char.upper(array)
print(upper_array)

lower_array = np.char.lower(array)
print(lower_array)

title_array = np.char.title(array)
print(title_array)

['python' 'numpy' 'pandas']
['PYTHON' 'NUMPY' 'PANDAS']
['python' 'numpy' 'pandas']
['Python' 'Numpy' 'Pandas']


In [34]:
# 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

# Ans(6)
import numpy as np

array = np.array(['python', 'numpy'])
print(array)

space_array = np.char.join(" ", array)
print(space_array)

['python' 'numpy']
['p y t h o n' 'n u m p y']


In [54]:
# 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, 
# and division.

# Ans(7)
import numpy as np 

arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

print(arr1)
print("\n",arr2,"\n")

addition = arr1 + arr2
print(addition,"\n")

subtraction = arr1 - arr2
print(subtraction,"\n")

multiplication = arr1 * arr2
print(multiplication,"\n")

division = arr1/arr2
print(division)

[[1 2 3]
 [4 5 6]]

 [[ 7  8  9]
 [10 11 12]] 

[[ 8 10 12]
 [14 16 18]] 

[[-6 -6 -6]
 [-6 -6 -6]] 

[[ 7 16 27]
 [40 55 72]] 

[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [60]:
# 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

# Ans(8)
import numpy as np

identity_matrix = np.eye(5)
print(identity_matrix,"\n")

diagonal_elements = np.diag(identity_matrix)
print(diagonal_elements)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 

[1. 1. 1. 1. 1.]


In [75]:
# 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all
# prime numbers in this array

# Ans(9)
import numpy as np 

array = np.random.randint(0,1001, size = 100)
print(array)

#function for prime numbers

def is_prime(n):
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True

primes = np.array([num for num in array if is_prime(num)])
print("\n",primes)

[547 846 700 686 111 391 823 298 222 607 375 754 693 177 103 933 790 443
 932 662 142 879 405 935 767 629  53  16 513 948 563 595 167 258  49 828
 926 265  60 396 630 220  64 645 651 192 581 145  54 953 593  74 399 303
 318 868 108 719 908 254 846 162  31 804 845 196 741 955 783  54 449 286
 710 869 990 435  61 183 125  71 922 179 389 787 933 392 406 478 433 523
 749 291 412 782 998  38 462 465  26 733]

 [547 823 607 103 443  53 563 167 953 593 719  31 449  61  71 179 389 787
 433 523 733]


In [83]:
# 10. Create a NumPy array representing daily temperatures for a month. Calculate and
# display the weekly averages.

# Ans(10)

import numpy as np 

# Generate a NumPy array representing daily temperatures for a month (30 days)
# For demonstration, we'll use random temperatures between -10 and 35 degrees Celsius
daily_temperatures = np.random.randint(-10,35,size = (28))
print(daily_temperatures,"\n")


# Reshape the array into a 2D array where each row represents a week (4 weeks)
# Since we have 30 days, we will have 4 full weeks and 2 extra days
daily_temperatures_reshaped = daily_temperatures.reshape(4,7)
print(daily_temperatures_reshaped,"\n")


# Calculate weekly averages
weekly_averages = np.mean(daily_temperatures_reshaped, axis = 1)
print(weekly_averages)

[ 34  13   3  18   3  21  -6  -9  23  -5   1  27  13  15  -1  22  14  33
  -6  27   1  20  29  32 -10  22  -7  29] 

[[ 34  13   3  18   3  21  -6]
 [ -9  23  -5   1  27  13  15]
 [ -1  22  14  33  -6  27   1]
 [ 20  29  32 -10  22  -7  29]] 

[12.28571429  9.28571429 12.85714286 16.42857143]
